version: "0.1"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: bff-api
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - GRPC_SERVICE_ADDRESS=localhost:50051
      - API_PORT=8080
    networks:
      - bff-network
    restart: unless-stopped

networks:
  bff-network:
    driver: bridge

